import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import NavigationPanel from "@/app/ui/navbar";
import {SessionProvider} from "next-auth/react";
import {auth} from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <SessionProvider session={session}>
            <html lang="en">
            <body className={inter.className}>
            <Providers>
                <NavigationPanel/>
                <main className='p-8'>{children}</main>
            </Providers>
            </body>
            </html>
        </SessionProvider>
    );
}
